[package]
name = "kifuwarabe_shogi2018"
version = "0.1.0"
authors = ["muzudho <muzudho1@gmail.com>"]
edition = "2018"

[dependencies]

rand = "0.7.3"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.7"
