[engine]

# 将棋ソフトの表示名です。 後ろにバージョン番号が付くなどの加工があることがあります。
# 大会出場時 "Kifuwarabe WCSC28"
name = "Kifuwarust"

# 将棋ソフトの制作者名です。
# 大会出場時 "TAKAHASHI, Satoshi" 作者の名前。姓・名の順にしたいぜ☆（＾～＾）異文化に通じる表記方法はないものか☆（＾～＾）
author = "Satoshi TAKAHASHI"

[resources]

log_file = "kifuwarabe_WCSC28.log"
log_enabled = true
